---
- name: activate rescue mode
  delegate_to: localhost
  uri:
    url: "https://robot-ws.your-server.de/boot/{{ ansible_host }}/rescue"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "os=linux&arch=64&authorized_key[]={{ hetzner_installimage_key_fingerprint }}"
    status_code: 200
    headers:
      Content-Type: application/x-www-form-urlencoded
  register: activated

- name: Execute hardware reset
  delegate_to: localhost
  uri:
    url: "https://robot-ws.your-server.de/reset/{{ ansible_host }}"
    method: POST
    user: "{{ hetzner_installimage_webservice_username }}"
    password: "{{ hetzner_installimage_webservice_password }}"
    force_basic_auth: yes
    body: "type=hw"
    status_code: 200
    headers:
      Content-Type: application/x-www-form-urlencoded
  register: reset

- name: remove server from local known_hosts file
  local_action: shell ssh-keygen -R {{ ansible_host }}

- name: pause a bit for the hardware reset to kick in
  pause: seconds=15

- name: waiting for server to come back
  local_action: wait_for
    host={{ ansible_host }}
    port=22
    delay=1
    timeout=180

...
